version: "3.6"
services:
  aditikharel-portfolio:
    build:
      context: $PWD/../..
      dockerfile: $PWD/aditikharel-portfolio/Dockerfile
    restart: always
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=aditikharel.com.np, www.gregsithole.com.np
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=aditikharel.com, www.aditikharel.com.np
      - LETSENCRYPT_EMAIL=aditikharel246@gmail.com
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    depends_on:
      - /aditikharel-portfolio
    links:
      - /aditikharel-portfolio

networks:
  default:
    external:
      name: nginx-proxy